import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "./styles.module.scss"

import Logo from "public/aerolab-logo.svg"
import Coin from "public/icons/coin.svg"
import Store from "components/Store"
import { useContext, useState } from "react"
import { UserContext } from "context/user"
import BalanceOptions from "components/BalanceOptions"

const Home: NextPage = () => {
  const { user } = useContext(UserContext)
  const [showBalanceOptions, setShowBalanceOptions] = useState<boolean>(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>Aerolab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.top_bar}>
          <Image src={Logo} alt={"Orange flyer"} />
          {user ? (
            <span className={styles.user_name}>{user.name}</span>
          ) : (
            <span className={styles.user_name}>User</span>
          )}
          <div
            className={styles.coin_container}
            onClick={() => setShowBalanceOptions(!showBalanceOptions)}
          >
            {user ? (
              <span className={styles.coin_counter}>{user.points}</span>
            ) : (
              <span className={styles.coin_counter}>0</span>
            )}
            <Image src={Coin} alt={"Gold Coin"} />
          </div>
          <BalanceOptions
            show={showBalanceOptions}
            setShow={setShowBalanceOptions}
          />
        </div>
        <Image
          src={"/header-x1.png"}
          width={2880}
          height={920}
          alt={"Blue headphones on a light blue background"}
          layout={"responsive"}
        />
      </header>
      <Store />
    </div>
  )
}

export default Home
