import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "./styles.module.scss"
import StoreElement from "components/Product"

import { useContext } from "react"
import { StoreContext } from "context/store"
import { StoreNav } from "components/StoreNav"

const Home: NextPage = () => {
  const { store } = useContext(StoreContext)

  return (
    <div className={styles.container}>
      <Head>
        <title>Aerolab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.banner}>
        <Image
          src={"/header-x1.png"}
          width={2880}
          height={920}
          alt={"Blue headphones on a light blue background"}
          layout={"responsive"}
        />
        <span className={styles.section_name}>Electronics</span>
      </section>
      <main className={styles.background}>
        <StoreNav bottomNav={false} />
        <ul className={styles.stand}>
          {store?.list.map((elem) => (
            <StoreElement key={elem._id} data={elem} />
          ))}
        </ul>
        <StoreNav bottomNav={true} />
      </main>
    </div>
  )
}

export default Home
